---
- name: install flatpak
  package:
    name: flatpak
    state: present

- name: add flathub remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install wanted flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ flatpak_install }}"
