---
- name: add chrome repo
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    skip_if_unavailable: True
    gpgcheck: 1
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: 1
    #enabled_metadata=1
    state: present
  when:
    - ansible_distribution == 'Fedora'
- name: install chrome
  package:
    name: google-chrome
    state: present
